classDiagram
    class CookieHelper {
        +isAllowed() bool
        +setCookie() void
    }

    class User {
        -email string
        -password string
        -errors array
        +validate() bool
        +login() bool
        +get(email,password) User
        +logout() void
        +isLoggedIn() bool
    }

    CookieHelper --> User
